---
version: "3.9"

services:

  materialized:
    image: materialize/materialized:latest
    container_name: materialized
    ports:
      - 6875:6875
      - 6878:6878
    healthcheck: {test: curl -f localhost:6878/api/readyz, interval: 1s, start_period: 30s}

  zookeeper:
    image: quay.io/debezium/zookeeper:1.9
    container_name: zookeeper
    ports:
     - 2181:2181
     - 2888:2888
     - 3888:3888

  kafka:
    image: quay.io/debezium/kafka:1.9
    container_name: kafka
    ports:
     - 9092:9092
    links:
     - zookeeper
    environment:
     - ZOOKEEPER_CONNECT=zookeeper:2181
     - CREATE_TOPICS=topic1:1:2,topic2:1:2

  schema-registry:
    image: confluentinc/cp-schema-registry:7.2.0
    container_name: schema-registry
    ports:
      - 8081:8081
    depends_on:
      - kafka
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: kafka:9092
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_LISTENERS: http://schema-registry:8081,http://localhost:8081

  provider:
    build:
      context: .
    container_name: provider
    depends_on:
      materialized: {condition: service_healthy}
    volumes:
      - ./integration:/usr/src/app/integration
    command: >
      sh -c "tail -F /dev/null"