---
version: "3.9"

services:

  materialized:
    image: materialize/materialized:latest
    container_name: materialized
    ports:
      - 6875:6875
      - 6878:6878
    healthcheck: {test: curl -f localhost:6878/api/readyz, interval: 1s, start_period: 30s}

  provider:
    build:
      context: .
    container_name: provider
    depends_on:
      materialized: {condition: service_healthy}
    volumes:
      - ./integration:/usr/src/app/integration
    environment:
      TF_LOG: INFO
    command: >
      sh -c "tail -F /dev/null"