name: documentation
on:
  pull_request:
    paths:
      - pkg/**
      - examples/**
      - templates/**
      - README.md

jobs:
  documentation:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version-file: "go.mod"
          cache: true

      - run: go mod download

      - run: go generate ./...

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Terraform Docs
