name: ids-migration-test
on:
  pull_request:
    paths:
      - pkg/**
      - integration/**
      - main.go
      - go.mod

jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Docker Compose Up
        run: docker compose up --build -d

      # Update main.tf for the latest stable provider version
      - name: Update main.tf for stable provider
        run: docker exec provider sed -i 's|source = "materialize.com/devex/materialize"|source = "MaterializeInc/materialize"|' main.tf

      # Terraform Init and Apply with the stable provider
      - name: Terraform Init with Stable Provider
        run: docker exec provider terraform init

      - name: Terraform Apply with Stable Provider
        run: docker exec provider terraform apply -auto-approve -compact-warnings

      # Revert main.tf to use the current version
      - name: Revert main.tf to current provider
        run: docker exec provider sed -i 's|source = "MaterializeInc/materialize"|source = "materialize.com/devex/materialize"|' main.tf

      # Terraform Init and Apply with the current provider version
      - name: Terraform Init with Current Provider
        run: docker exec provider terraform init -upgrade

      - name: Terraform Apply with Current Provider
        run: docker exec provider terraform apply -auto-approve -compact-warnings

      # Additional steps
      - name: Terraform Plan
        run: docker exec provider terraform plan -detailed-exitcode

      - name: Terraform Destroy
        run: docker exec provider terraform destroy -auto-approve -compact-warnings

      - name: Docker Compose Down
        run: docker compose down
