name: integration
on:
  pull_request:
    paths:
      - materialize/**

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Docker Compose Up
        run: docker compose up --build -d

      - name: Terraform Init
        run: |
          docker exec provider terraform init

      - name: Secret (Create)
        run: |
          docker exec provider terraform apply -target=materialize_secret.example_secret -auto-approve -compact-warnings
      
      - name: Secret (Destroy)
        run: |
          docker exec provider terraform destroy -target=materialize_secret.example_secret -auto-approve -compact-warnings

      - name: Docker Compose Down
        run: docker compose down